name: Run Vitest Tests

on:
  push:
    branches: [ main ] # Or your primary branch, e.g., master
  pull_request:
    branches: [ main ] # Or your primary branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Test only on Node.js 20.x

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use ci for cleaner installs in CI environments

    - name: Run tests
      run: npm test

    # Optional: Upload coverage reports if generated
    # - name: Upload coverage reports
    #   if: always() # Run this step even if previous steps fail
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: coverage-report-${{ matrix.node-version }}
    #     path: coverage/ # Path to Vitest coverage output directory
    #     retention-days: 7

    # Optional: Upload HTML report if generated
    # - name: Upload HTML test report
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: html-report-${{ matrix.node-version }}
    #     path: html/ # Path to Vitest HTML report output directory
    #     retention-days: 7
